import { rateLimit, RATE_LIMITS } from '@/lib/rateLimit';
export const dynamic = 'force-dynamic';

import { createPublicClient, createWalletClient, http, parseGwei, type Address, type Hex } from 'viem';
import { privateKeyToAccount } from 'viem/accounts';

import { ApiError } from '@/lib/api/errors';
import { json, jsonError } from '@/lib/api/routeUtils';
import { requireAdmin } from '@/lib/adminAuth';
import { logAdminAction } from '@/lib/adminAudit';
import { BASE, BASE_RPC_URL } from '@/lib/contracts/bbb4';
import {
  BBB4_BATCH_PROOF_BYTECODE,
  BBB4_BATCH_PROOF_ABI,
} from '@/lib/contracts/bbb4BatchProofArtifact';
import { getAdminFirestore, isFirestoreConfigured } from '@/lib/firebaseAdmin';
import { logger } from '@/lib/logger';
import { getRequestId } from '@/lib/requestId';

const SYSTEM_CONFIG = 'system_config';
const BATCH_PROOF_DOC = 'batchProof';

// Pinned gas params consistent with the rest of the admin signer flows.
// Base mainnet basefee is consistently <0.01 gwei; 0.1 gwei maxFee is plenty
// of margin and keeps us well below the wallet's ~0.002 ETH balance even
// for a contract deploy (~600k gas).
const BASE_GAS_PARAMS = {
  maxFeePerGas: parseGwei('0.1'),
  maxPriorityFeePerGas: parseGwei('0.001'),
};

function loadPrivateKey(): Hex | null {
  const raw = process.env.BBB4_OWNER_PRIVATE_KEY?.trim();
  if (!raw) return null;
  const hex = raw.startsWith('0x') ? raw : `0x${raw}`;
  if (!/^0x[0-9a-fA-F]{64}$/.test(hex)) return null;
  return hex as Hex;
}

interface BatchProofConfig {
  contractAddress?: Address;
  deployerAddress?: Address;
  deployTxHash?: Hex;
  deployedAt?: number;
  ownerAddress?: Address;
}

/**
 * POST /api/admin/deploy-batch-proof
 *
 * One-off admin endpoint that deploys BBB4BatchProof.sol to Base mainnet
 * using the existing BBB4_OWNER_PRIVATE_KEY signer. The compiled bytecode +
 * ABI come from lib/contracts/bbb4BatchProofArtifact.ts (regenerated by
 * scripts/compile-batch-proof.js after any contract source change).
 *
 * Idempotent: if Firestore system_config/batchProof already has a contract
 * address that returns non-empty bytecode on Base, refuses the redeploy and
 * returns the existing address. Avoids accidentally double-deploying.
 *
 * After a successful deploy the contract address is persisted to:
 *   - system_config/batchProof (Firestore) — read by the frontend + Go API
 *   - admin_audit (Firestore)               — full audit trail
 *
 * The endpoint should be removed in a follow-up commit once the contract is
 * live, the same cleanup pattern as /api/admin/revoke-7702.
 */
export async function POST(req: Request) {
  const requestId = getRequestId(req);
  const rateLimited = rateLimit(req, RATE_LIMITS.admin);
  if (rateLimited) return rateLimited;

  let actorWallet = '';
  try {
    const admin = await requireAdmin(req);
    actorWallet = admin.walletAddress ?? admin.userId;

    const key = loadPrivateKey();
    if (!key) return jsonError('BBB4_OWNER_PRIVATE_KEY not configured', 503);

    const account = privateKeyToAccount(key);
    const publicClient = createPublicClient({ chain: BASE, transport: http(BASE_RPC_URL) });

    // Idempotency: bail if we already have a deployed contract on file.
    if (isFirestoreConfigured()) {
      const db = getAdminFirestore();
      const snap = await db.collection(SYSTEM_CONFIG).doc(BATCH_PROOF_DOC).get();
      if (snap.exists) {
        const existing = snap.data() as BatchProofConfig | undefined;
        if (existing?.contractAddress) {
          const code = await publicClient.getCode({ address: existing.contractAddress });
          if (code && code !== '0x') {
            logger.info('admin.deploy_batch_proof.already_deployed', {
              requestId,
              actor: actorWallet,
              address: existing.contractAddress,
            });
            return json({
              success: true,
              alreadyDeployed: true,
              contractAddress: existing.contractAddress,
              deployTxHash: existing.deployTxHash ?? null,
              deployerAddress: existing.deployerAddress ?? null,
              note: 'Contract already deployed — refusing to redeploy. Delete system_config/batchProof in Firestore to allow a fresh deploy.',
              requestId,
            });
          }
        }
      }
    }

    // Pre-flight: confirm signer has at least 0.0005 ETH for gas.
    const balance = await publicClient.getBalance({ address: account.address });
    const minWei = 500_000_000_000_000n; // 0.0005 ETH
    if (balance < minWei) {
      return jsonError(
        `Admin wallet ${account.address} has ${balance} wei (~${Number(balance) / 1e18} ETH); need at least 0.0005 ETH for deploy gas.`,
        400,
      );
    }

    const walletClient = createWalletClient({
      account,
      chain: BASE,
      transport: http(BASE_RPC_URL),
    });

    logger.info('admin.deploy_batch_proof.submitting', {
      requestId,
      actor: actorWallet,
      from: account.address,
      bytecodeBytes: (BBB4_BATCH_PROOF_BYTECODE.length - 2) / 2,
    });

    // Constructor arg: initialOwner. Use the same admin wallet as the
    // contract owner — keeps operational simplicity (one signer for
    // commit/publishSlots/reveal).
    const txHash = await walletClient.deployContract({
      abi: BBB4_BATCH_PROOF_ABI,
      bytecode: BBB4_BATCH_PROOF_BYTECODE,
      args: [account.address],
      ...BASE_GAS_PARAMS,
    });

    const receipt = await publicClient.waitForTransactionReceipt({ hash: txHash });
    if (receipt.status !== 'success' || !receipt.contractAddress) {
      throw new ApiError(500, `Deploy transaction reverted: ${txHash}`);
    }
    const contractAddress = receipt.contractAddress;

    // Persist to Firestore so the frontend + Go API can read the address
    // without a Vercel env var redeploy. Setting NEXT_PUBLIC_BBB4_BATCH_PROOF_ADDRESS
    // is still recommended for client-side reads but not required.
    if (isFirestoreConfigured()) {
      const db = getAdminFirestore();
      const config: BatchProofConfig = {
        contractAddress,
        deployerAddress: account.address,
        deployTxHash: txHash,
        deployedAt: Date.now(),
        ownerAddress: account.address,
      };
      await db.collection(SYSTEM_CONFIG).doc(BATCH_PROOF_DOC).set(config, { merge: true });
    }

    await logAdminAction({
      actor: actorWallet,
      action: 'deploy-batch-proof',
      target: contractAddress,
      after: {
        contractAddress,
        deployTxHash: txHash,
        deployerAddress: account.address,
        gasUsed: receipt.gasUsed.toString(),
        blockNumber: Number(receipt.blockNumber),
      },
      requestId,
    });

    logger.info('admin.deploy_batch_proof.success', {
      requestId,
      actor: actorWallet,
      contractAddress,
      txHash,
    });

    return json({
      success: true,
      contractAddress,
      deployTxHash: txHash,
      deployerAddress: account.address,
      blockNumber: Number(receipt.blockNumber),
      gasUsed: receipt.gasUsed.toString(),
      basescanContract: `https://basescan.org/address/${contractAddress}`,
      basescanTx: `https://basescan.org/tx/${txHash}`,
      requestId,
    });
  } catch (err) {
    logger.error('admin.deploy_batch_proof.failed', { requestId, actor: actorWallet, err });
    if (err instanceof ApiError) return jsonError(err.message, err.status, { requestId });
    return jsonError((err as Error).message || 'Internal Server Error', 500, { requestId });
  }
}
