steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile', '-t', 'gcr.io/$PROJECT_ID/sbs-drafts-api:$SHORT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sbs-drafts-api:$SHORT_SHA']
images:
  - 'gcr.io/$PROJECT_ID/sbs-drafts-api:$SHORT_SHA'
